version: '3.8'

services:
  api:
    container_name: MyanvieBE
    build:
      context: .
      dockerfile: MyanvieBE/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
      - minio
      - mailhog

  postgres:
    container_name: shop-postgres-db
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    container_name: shop-minio-storage
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASS}
    volumes:
      - minio_data:/data

  mailhog: # <-- ĐẢM BẢO SERVICE NÀY CÓ (HOẶC ĐƯỢC BỎ COMMENT)
    image: mailhog/mailhog:latest
    container_name: myanvie-mailhog
    ports:
      - "1025:1025" # Cổng SMTP mà MailHog lắng nghe
      - "8025:8025" # Cổng Web UI để xem email

    
volumes:
  postgres_data:
  minio_data: